version: 0.2

phases:
  install:
    commands:
      - echo "Installing..."
  build:
    commands:
      - echo "Deploying to S3..."

  post_build:
    commands:
      - aws s3 rm s3://nodejs-cicd-deploy-bucket-vaishnavi --recursive
      - aws s3 cp . s3://nodejs-cicd-deploy-bucket-vaishnavi --recursive

artifacts:
  files:
    - '**/*'
